### PR TITLE
ENH: Add repo scripts to the list of sirius repos.

### PR DESCRIPTION
**Pull request by fernandohds564**

### CODE REVIEW

**Comment by xresende** [comment]
@fernandohds564 , I thought we were not using this list anymore...

**Comment by fernandohds564** [comment]
@xresende, the script https://github.com/lnls-fac/scripts/blob/master/bin/sirius-lnls-gitall.py uses this list.
However, it can be changed instead.
I think it's better to remove this list if we want not to use it any more.

**Comment by xresende** [comment]
I think [sirius-lnls-gitall.py](https://github.com/lnls-fac/scripts/blob/master/bin/sirius-lnls-gitall.py ) is to be deprecated soon, now that we will use ansible.

**Comment by xresende** [comment]
We can postpone the decision of deleting the list in <code>siriuspy.envars</code> since you may still be using [https://github.com/lnls-fac/scripts/blob/master/bin/sirius-lnls-gitall.py](https://github.com/lnls-fac/scripts/blob/master/bin/sirius-lnls-gitall.py)

**Pull request merged**
