### PR TITLE
Updated RF PVs to SIRIUS standart naming system.

### PR DESCRIPTION
**Pull request by David-Daminelli**
Updated RF PVs to SIRIUS standart naming system. Commented out Flow Rates PVs from the Petra 7 Cavity.

### CODE REVIEW

**Comment by fernandohds564** [comment]
@David-Daminelli, have you tested this PR, trying to connect with the new PVs, to be sure that the names are all correct?

**Comment by xresende** [comment]
@David-Daminelli  , question: are some of these PVs also in `global_config`-type configurations ?

**Comment by anacso17** [comment]
> @David-Daminelli, have you tested this PR, trying to connect with the new PVs, to be sure that the names are all correct?

Hi guys, we are working now on running the new IOC version (with the new PV naming) for BO and SI A and B LLRF. We plan to test this soon.

**Comment by xresende** [comment]
@anacso17 , @David-Daminelli remeber to rename PVs in archiver appliance.

**Review by xresende — APPROVED** [review]

**Review by murilobalves — APPROVED** [review]

**Comment by fernandohds564** [comment]
Was this PR tested already?

**Pull request merged**
