### PR TITLE
Add ClientArchiver timeout setter/getter

### PR DESCRIPTION
**Pull request by xresende**

### CODE REVIEW

**Review by murilobalves — APPROVED** [review]

**Review by fernandohds564 — COMMENTED** [review]
@anacso17, @xresende what do you think about changing the interface so that an error is raised in case of timeout?

**Comment by anacso17** [comment]
> @anacso17, @xresende what do you think about changing the interface so that an error is raised in case of timeout?

We were indeed talking about this problem of not having a well documented return in case of empty returns. I think raising an error is a good choice for timeout cases

**Comment by xresende** [comment]
> @anacso17, @xresende what do you think about changing the interface so that an error is raised in case of timeout?

raising Timeout error.

**Review by fernandohds564 — APPROVED** [review]

**Review by anacso17 — APPROVED** [review]

**Review by fernandohds564 — APPROVED** [review]

**Comment by anacso17** [comment]
Hi guys, I just added some commits that:
- Fixed a bug observed when closing a Qt application that uses ClientArchiver
- Make ClientArchiver compatible for waveform data
- Replace plot_date with xaxis.axis_date, because matplotlib will discontinue plot_date in the future
- Change PVData to simply return None in case ClientArchiver receives an empty response

**Review by murilobalves — APPROVED** [review]

**Pull request merged**
